{
 "title": "pkg upgradable and broken",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "upgradable packages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "pkg_upgradable", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "broken packages",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "sum(pkg_broken)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "hosts need reboot",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "sum(pkg_reboot_required)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "packages upgradable cluster",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    { "expr": "sum(pkg_upgradable)", "legendFormat": "__auto" }
   ]
  }
 ]
}